typography_spectrum: 0.2280795539263636
content_rating:
  adult: false
color:
  brandStrength: 0.3724400559440255
  lightness: 0.09327386505901814
  saturation: 0.6112550771795213
  rhythmicContrast: 0.8961664051748812
  brandColors:
    - '#595241'
    - '#B8AE9C'
    - '#FFFFFF'
    - '#ACCFCC'
    - '#8A0917'
layout_spectrum: 0.7781631820835173
author:
  name: Chichi
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/f91f4b5a-8c98-4b81-a25d-e5c17d262072.png
name: N-Vade
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/de5c3494-6e33-402b-89fe-e0c70d4449e7.png
title: When Passion Meets Purpose You're Doing It
